export WP_HOST=local

export WC_KEY=[YOUR WORDPRESS KEY]
export WC_SECRET=[YOUR WORDPRESS SECRET]

export DB_USER=[YOUR DB USER]
export DB_PASSWORD=[YOUR DB PASSWORD]
export DB_USER_LOCAL=[YOUR DB USER]
export DB_PASSWORD_LOCAL=[YOUR DB PASSWORD]
export DB_USER_DEV=[YOUR DB USER]
export DB_PASSWORD_DEV=[YOUR DB PASSWORD]