services:
  db:
    image: mysql:latest
    container_name: wordpress_db
    # command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wp-admin
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    #expose:
    #  - 3306
    #  - 3306
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: my_wordpress
    volumes:
      - wp_data:/var/www/html
    ports:
      - 8888:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress-db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
volumes:
  db_data:
  wp_data: